### ISSUE TITLE
Description limited to 255 chars

### ISSUE THREAD

**Issue by nilsine** [etsy/etsyapi#102]
Hello,

I think I found a bug in the etsy API. When I use the API to update the
translation with "updateListingTranslation", the description seems to be
limited to 255 cars, below 255 I got a 200 OK and the translation is
correctly updated, above I got a 400 Bad request and the error message
"Value for description must be 255 characters or less." which is stupid
because on etsy.com we can of course put description longer than 255 car.

Actually this is the same bug as here:
https://groups.google.com/forum/#!searchin/etsy-api-v2/string$20255/etsy-api-v2/4Zum96vDujc/8nCvWgw9RjIJ
but for the translation.

**Comment by kjakubiuk** [comment]
Someone fix this bug reported almost a year ago? Or we have to manually put translations?

**Comment by kjakubiuk** [comment]
We really need this bug to be fix. 
Anyone from etsy?

**Comment by mdg** [comment]
Looking at this today.

**Comment by kjakubiuk** [comment]
Hi,
atlast - thank you. Now description is not limited but can't add tags in translation. We send tags, response code is 200 but now tags are added to items in translation.

**Comment by mdg** [comment]
This was fixed last week. @kjakubiuk please submit a new bug with a full description of what you're seeing for tags.

**Comment by mdg** [comment]
@kjakubiuk it might be caused by how you're sending the tags. If you're not already, try sending them as a comma separated list.
