### ISSUE TITLE
uploadListingImage gives an OK response however the data returned is binary and not a JSON text packet

### ISSUE THREAD

**Issue by gragra33** [etsy/etsyapi#103]
Hi Guys,

We are receiving reports of uploadListingImage deleteListingImage gives an OK response however the data returned is binary and not a JSON text packet. It appears that the image upload/delete is successful, only the data returned is bad.

How quickly can this be checked and resolved?

G.

**Comment by mdg** [comment]
Wasn't able to reproduce.
