### ISSUE TITLE
[BUG] Variation PropertySet return incorrectly formatted data [Originally reported 2/25/2015]

### ISSUE THREAD

**Issue by gragra33** [etsy/etsyapi#110]
!!! Due to the urgency of this problem, it was originally reported by email on February 25, 2015. Below is a copy of what was reported.

We are experiencing a fatal Etsy bug with PropertySet that is preventing our app from supporting Variation support. 

The JSON data result is not formed correctly as per the documentation (ref: https://www.etsy.com/developers/documentation/getting_started/variations#section_property_set_example & data def: https://www.etsy.com/developers/documentation/reference/variations_propertyset#section_fields ). It appears that a new category_id field was added and the implementation was incorrectly applied.

We are expecting an array of PropertySet resource however we're receiving a variant results array (PropertySet resource not correctly JSON encoded) - see data below and following visualisation of the bug.

![xxx](https://cloud.githubusercontent.com/assets/2926439/6433015/a14a5316-c0b8-11e4-9fbb-1081ee40805c.png)

An urgent bug fix is required.

SAMPLE ERROR JSON DATA RETURNED
---

{"count":5,"results":{"qualifying_properties":{"266817057":{"property_id":266817057,"name":"Recipient","input_name":"property[recipient]","label":"Who is it for?","param":"recipient_id","default_option":"Select a recipient...","description":"Recipient","is_custom":false,"title":"Recipient:"},"300":{"property_id":300,"name":"Sizing Scale","input_name":"property[sizing_scale]","label":"What scale are your sizes in?","param":"sizing_scale","default_option":"Select a scale...","description":"Sizing Scale","is_custom":false,"title":"Sizing Scale:"},"301":{"property_id":301,"name":"Weight Scale","input_name":"property[weight_scale]","label":"What scale are your weights in?","param":"weight_scale","default_option":"Select a weight scale...","description":"Weight Scale","is_custom":false,"title":"Weight Scale:"},"302":{"property_id":302,"name":"Sizing Scale","input_name":"property[diameter_scale]","label":"What scale are your sizes in?","param":"diameter_scale","default_option":"Select a scale...","description":"Sizing Scale","is_custom":false,"title":"Sizing Scale:"},"303":{"property_id":303,"name":"Sizing Scale","input_name":"property[dimensions_scale]","label":"What scale are your sizes in?","param":"dimensions_scale","default_option":"Select a scale...","description":"Sizing Scale","is_custom":false,"title":"Sizing Scale:"},"304":{"property_id":304,"name":"Sizing Scale","input_name":"property[height_scale]","label":"What scale are your sizes in?","param":"height_scale","default_option":"Select a scale...","description":"Sizing Scale","is_custom":false,"title":"Sizing Scale:"},"305":{"property_id":305,"name":"Sizing Scale","input_name":"property[length_scale]","label":"What scale are your sizes in?","param":"length_scale","default_option":"Select a scale...","description":"Sizing Scale","is_custom":false,"title":"Sizing Scale:"},"306":{"property_id":306,"name":"Sizing Scale","input_name":"property[width_scale]","label":"What scale are your sizes in?","param":"width_scale","default_option":"Select a scale...","description":"Sizing Scale","is_custom":false,"title":"Sizing Scale:"}},"options":{"266817059":"Men","266817061":"Women","266817065":"Unisex Adults","266817067":"Teen Boys","266817069":"Teen Girls","266817071":"Teens","266817073":"Boys","266817077":"Girls","266817079":"Children","266817081":"Baby Boys","266817083":"Baby Girls","266817085":"Babies","266817087":"Birds","301958802":"Cats","301959052":"Dogs","301959242":"Pets","400":"UK Ring Size","377":"JP","376":"EU","375":"UK","374":"JP","373":"EU","372":"UK","371":"JP","370":"EU","369":"UK","368":"JP","367":"EU","366":"UK","365":"JP","364":"EU","363":"UK","362":"US","361":"EU","378":"UK","379":"EU","380":"JP","399":"EU","398":"JP","397":"EU","396":"UK","395":"JP","394":"EU","393":"JP","392":"EU","391":"UK","388":"EU","387":"UK","386":"JP","385":"EU","384":"UK","383":"JP","382":"EU","381":"UK","360":"JP","359":"UK","358":"JP","389":"JP","301":"Alpha","335":"Fluid Ounces","353":"UK","354":"EU","356":"UK","357":"EU","355":"JP","302":"US","336":"Millilitres","303":"Months","337":"Litres","304":"Years","305":"US","306":"US","307":"US","308":"US","309":"US","310":"US","311":"US","312":"US","313":"US Plus Size","314":"US","315":"US","316":"US","317":"US","318":"US","319":"US","320":"US","321":"US","322":"US","323":"US","324":"US","325":"US","327":"Inches","326":"US","328":"Centimeters","329":"Other","330":"US Ring Size","331":"Ounces","332":"Pounds","333":"Grams","334":"Kilograms","341":"Inches","342":"Centimeters","343":"Other","344":"Inches","345":"Centimeters","346":"Other","347":"Inches","348":"Centimeters","349":"Other","350":"Inches","351":"Centimeters","352":"Other","338":"Inches","339":"Centimeters","340":"Other"},"properties":{"200":{"property_id":200,"name":"Color","input_name":null,"label":null,"param":null,"default_option":null,"description":"Color","is_custom":false,"title":"Color:"},"504":{"property_id":504,"name":"Diameter","input_name":null,"label":null,"param":null,"default_option":null,"description":"Diameter","is_custom":false,"title":"Diameter:"},"501":{"property_id":501,"name":"Dimensions","input_name":null,"label":null,"param":null,"default_option":null,"description":"Dimensions","is_custom":false,"title":"Dimensions:"},"502":{"property_id":502,"name":"Fabric","input_name":null,"label":null,"param":null,"default_option":null,"description":"Fabric","is_custom":false,"title":"Fabric:"},"500":{"property_id":500,"name":"Finish","input_name":null,"label":null,"param":null,"default_option":null,"description":"Finish","is_custom":false,"title":"Finish:"},"503":{"property_id":503,"name":"Flavor","input_name":null,"label":null,"param":null,"default_option":null,"description":"Flavor","is_custom":false,"title":"Flavor:"},"505":{"property_id":505,"name":"Height","input_name":null,"label":null,"param":null,"default_option":null,"description":"Height","is_custom":false,"title":"Height:"},"506":{"property_id":506,"name":"Length","input_name":null,"label":null,"param":null,"default_option":null,"description":"Length","is_custom":false,"title":"Length:"},"507":{"property_id":507,"name":"Material","input_name":null,"label":null,"param":null,"default_option":null,"description":"Material","is_custom":false,"title":"Material:"},"508":{"property_id":508,"name":"Pattern","input_name":null,"label":null,"param":null,"default_option":null,"description":"Pattern","is_custom":false,"title":"Pattern:"},"509":{"property_id":509,"name":"Scent","input_name":null,"label":null,"param":null,"default_option":null,"description":"Scent","is_custom":false,"title":"Scent:"},"100":{"property_id":100,"name":"Size","input_name":null,"label":null,"param":null,"default_option":null,"description":"Size","is_custom":false,"title":"Size:"},"510":{"property_id":510,"name":"Style","input_name":null,"label":null,"param":null,"default_option":null,"description":"Style","is_custom":false,"title":"Style:"},"511":{"property_id":511,"name":"Weight","input_name":null,"label":null,"param":null,"default_option":null,"description":"Weight","is_custom":false,"title":"Weight:"},"512":{"property_id":512,"name":"Width","input_name":null,"label":null,"param":null,"default_option":null,"description":"Width","is_custom":false,"title":"Width:"},"513":{"property_id":513,"name":"Custom Property","input_name":null,"label":null,"param":null,"default_option":null,"description":"Custom Property","is_custom":true,"title":"Custom Property:"},"514":{"property_id":514,"name":"Custom Property","input_name":null,"label":null,"param":null,"default_option":null,"description":"Custom Property","is_custom":true,"title":"Custom Property:"},"515":{"property_id":515,"name":"Device","input_name":null,"label":null,"param":null,"default_option":null,"description":"Device","is_custom":false,"title":"Device:"}},"qualifiers":{"504":[{"property_id":302,"results":null,"aliases":null,"options":[341,342,343]}],"505":[{"property_id":304,"results":null,"aliases":null,"options":[347,348,349]}],"100":[{"property_id":300,"results":null,"aliases":null,"options":[301,327,328,335,336,337,329]}],"512":[{"property_id":306,"results":null,"aliases":null,"options":[338,339,340]}],"511":[{"property_id":301,"results":null,"aliases":null,"options":[332,331,333,334]}],"506":[{"property_id":305,"results":null,"aliases":null,"options":[350,351,352]}],"501":[{"property_id":303,"results":null,"aliases":null,"options":[344,345,346]}]},"category_id":null},"params":{"category_id":null,"taxonomy_id":null,"recipient_id":null},"type":"Variations_PropertySet","pagination":{}}

**Comment by gragra33** [comment]
Any support for this bug from Etsy? It is a fatal breaking change that stops support for editing and creating variations and requires urgent attention.

**Comment by gragra33** [comment]
Is there any update when this bug will be fixed? It's already been over a week and we have not heard anything from Etsy.

**Comment by mdg** [comment]
Hi Graeme,
As I understand this description, you object to the API response having a new field. Is that correct? New fields are additive and do not change what is already there. Therefore, we do not consider new fields to be backwards incompatible changes. The expectation is that apps will ignore fields that they do not know how to handle. Please let me know if I've misunderstood your report.

**Comment by gragra33** [comment]
Hi Matt,

No, Tha is not correct. The data structure broke when the new field was added. The json data returned is not an array of PropertySet objects anymore.

Kind regards,

Graeme

Sent from my Windows Phone
________________________________

**Comment by gragra33** [comment]
Matt,

This is what you are currently sending:

![mattbug1](https://cloud.githubusercontent.com/assets/2926439/6565659/f56a5970-c705-11e4-8192-b64d3710fe38.png)

And this is what we SHOULD BE seeing [mocked from Etsy API documentation & our source code as no stored real packets]:

![mattbug2](https://cloud.githubusercontent.com/assets/2926439/6565701/2c57ed1c-c706-11e4-84d5-6678e4583c4e.png)

Two this to note here:

1. The bug does not return a well-formed JSON packet as either single object of PropertySet or as an Array of PropertySet
2. The properyset_id is missing from the results.

Please reopen this bug report as the bug is not resolved and a fix is required ASAP.

**Comment by gragra33** [comment]
Hi Matt,
 
I am still confused as to why you closed the bug report unfixed when Sara clearly stated in an email to us that "We've [Etsy] identified the change that started causing problems for you, and we're working on a fix.".
 
I've updated the bug report with more visual-aid data to better assist you with describing this bug. 
 
Please advise how quickly this can be resolved.
 
Thanks,
 
Graeme

 
To: reply@reply.github.com
From: gragra33@hotmail.com
Subject: RE: [etsyapi] [BUG] Variation PropertySet return incorrectly formatted data [Originally reported 2/25/2015] (#110)
Date: Tue, 10 Mar 2015 08:18:14 +1100







Hi Matt,



No, Tha is not correct. The data structure broke when the new field was added. The json data returned is not an array of PropertySet objects anymore.



Kind regards,



Graeme



Sent from my Windows Phone



From:
Matthew Graham

Sent:
ý10/ý03/ý2015 4:05 AM

To:
etsy/etsyapi

Cc:
Graeme

Subject:
Re: [etsyapi] [BUG] Variation PropertySet return incorrectly formatted data [Originally reported 2/25/2015] (#110)





Hi Graeme,

As I understand this description, you object to the API response having a new field. Is that correct? New fields are additive and do not change what is already there. Therefore, we do not consider new fields to be backwards incompatible changes. The expectation
 is that apps will ignore fields that they do not know how to handle. Please let me know if I've misunderstood your report.

—

Reply to this email directly or 
view it on GitHub.

**Comment by mdg** [comment]
Thanks Graeme, I understand what you're describing now.

**Comment by gragra33** [comment]
Thanks Matt... We are looking forward to closing this one too.

**Comment by amitsnyderman** [comment]
This should be resolved. Please let us know if you continue to see an issue. Thanks.

**Comment by gragra33** [comment]
Thanks for letting me know however there appears to be no change to the data returned - here is the results from the test just run:

![xxxx111](https://cloud.githubusercontent.com/assets/2926439/6590912/713a1a2a-c80c-11e4-8118-7090622d1e2f.png)

And here is the raw data received:

{"count":5,"results":{"qualifying_properties":{"266817057":{"property_id":266817057,"name":"Recipient","input_name":"property[recipient]","label":"Who is it for?","param":"recipient_id","default_option":"Select a recipient...","description":"Recipient","is_custom":false,"title":"Recipient:"},"300":{"property_id":300,"name":"Sizing Scale","input_name":"property[sizing_scale]","label":"What scale are your sizes in?","param":"sizing_scale","default_option":"Select a scale...","description":"Sizing Scale","is_custom":false,"title":"Sizing Scale:"},"301":{"property_id":301,"name":"Weight Scale","input_name":"property[weight_scale]","label":"What scale are your weights in?","param":"weight_scale","default_option":"Select a weight scale...","description":"Weight Scale","is_custom":false,"title":"Weight Scale:"},"302":{"property_id":302,"name":"Sizing Scale","input_name":"property[diameter_scale]","label":"What scale are your sizes in?","param":"diameter_scale","default_option":"Select a scale...","description":"Sizing Scale","is_custom":false,"title":"Sizing Scale:"},"303":{"property_id":303,"name":"Sizing Scale","input_name":"property[dimensions_scale]","label":"What scale are your sizes in?","param":"dimensions_scale","default_option":"Select a scale...","description":"Sizing Scale","is_custom":false,"title":"Sizing Scale:"},"304":{"property_id":304,"name":"Sizing Scale","input_name":"property[height_scale]","label":"What scale are your sizes in?","param":"height_scale","default_option":"Select a scale...","description":"Sizing Scale","is_custom":false,"title":"Sizing Scale:"},"305":{"property_id":305,"name":"Sizing Scale","input_name":"property[length_scale]","label":"What scale are your sizes in?","param":"length_scale","default_option":"Select a scale...","description":"Sizing Scale","is_custom":false,"title":"Sizing Scale:"},"306":{"property_id":306,"name":"Sizing Scale","input_name":"property[width_scale]","label":"What scale are your sizes in?","param":"width_scale","default_option":"Select a scale...","description":"Sizing Scale","is_custom":false,"title":"Sizing Scale:"}},"options":{"266817059":"Men","266817061":"Women","266817065":"Unisex Adults","266817067":"Teen Boys","266817069":"Teen Girls","266817071":"Teens","266817073":"Boys","266817077":"Girls","266817079":"Children","266817081":"Baby Boys","266817083":"Baby Girls","266817085":"Babies","266817087":"Birds","301958802":"Cats","301959052":"Dogs","301959242":"Pets","302326609":"Not specified","400":"UK Ring Size","377":"JP","376":"EU","375":"UK","374":"JP","373":"EU","372":"UK","371":"JP","370":"EU","369":"UK","368":"JP","367":"EU","366":"UK","365":"JP","364":"EU","363":"UK","362":"US","361":"EU","378":"UK","379":"EU","380":"JP","399":"EU","398":"JP","397":"EU","396":"UK","395":"JP","394":"EU","393":"JP","392":"EU","391":"UK","388":"EU","387":"UK","386":"JP","385":"EU","384":"UK","383":"JP","382":"EU","381":"UK","360":"JP","359":"UK","358":"JP","389":"JP","301":"Alpha","335":"Fluid Ounces","353":"UK","354":"EU","356":"UK","357":"EU","355":"JP","302":"US","336":"Millilitres","303":"Months","337":"Litres","304":"Years","305":"US","306":"US","307":"US","308":"US","309":"US","310":"US","311":"US","312":"US","313":"US Plus Size","314":"US","315":"US","316":"US","317":"US","318":"US","319":"US","320":"US","321":"US","322":"US","323":"US","324":"US","325":"US","327":"Inches","326":"US","328":"Centimeters","329":"Other","330":"US Ring Size","331":"Ounces","332":"Pounds","333":"Grams","334":"Kilograms","341":"Inches","342":"Centimeters","343":"Other","344":"Inches","345":"Centimeters","346":"Other","347":"Inches","348":"Centimeters","349":"Other","350":"Inches","351":"Centimeters","352":"Other","338":"Inches","339":"Centimeters","340":"Other"},"properties":{"200":{"property_id":200,"name":"Color","input_name":null,"label":null,"param":null,"default_option":null,"description":"Color","is_custom":false,"title":"Color:"},"504":{"property_id":504,"name":"Diameter","input_name":null,"label":null,"param":null,"default_option":null,"description":"Diameter","is_custom":false,"title":"Diameter:"},"501":{"property_id":501,"name":"Dimensions","input_name":null,"label":null,"param":null,"default_option":null,"description":"Dimensions","is_custom":false,"title":"Dimensions:"},"502":{"property_id":502,"name":"Fabric","input_name":null,"label":null,"param":null,"default_option":null,"description":"Fabric","is_custom":false,"title":"Fabric:"},"500":{"property_id":500,"name":"Finish","input_name":null,"label":null,"param":null,"default_option":null,"description":"Finish","is_custom":false,"title":"Finish:"},"503":{"property_id":503,"name":"Flavor","input_name":null,"label":null,"param":null,"default_option":null,"description":"Flavor","is_custom":false,"title":"Flavor:"},"505":{"property_id":505,"name":"Height","input_name":null,"label":null,"param":null,"default_option":null,"description":"Height","is_custom":false,"title":"Height:"},"506":{"property_id":506,"name":"Length","input_name":null,"label":null,"param":null,"default_option":null,"description":"Length","is_custom":false,"title":"Length:"},"507":{"property_id":507,"name":"Material","input_name":null,"label":null,"param":null,"default_option":null,"description":"Material","is_custom":false,"title":"Material:"},"508":{"property_id":508,"name":"Pattern","input_name":null,"label":null,"param":null,"default_option":null,"description":"Pattern","is_custom":false,"title":"Pattern:"},"509":{"property_id":509,"name":"Scent","input_name":null,"label":null,"param":null,"default_option":null,"description":"Scent","is_custom":false,"title":"Scent:"},"100":{"property_id":100,"name":"Size","input_name":null,"label":null,"param":null,"default_option":null,"description":"Size","is_custom":false,"title":"Size:"},"510":{"property_id":510,"name":"Style","input_name":null,"label":null,"param":null,"default_option":null,"description":"Style","is_custom":false,"title":"Style:"},"511":{"property_id":511,"name":"Weight","input_name":null,"label":null,"param":null,"default_option":null,"description":"Weight","is_custom":false,"title":"Weight:"},"512":{"property_id":512,"name":"Width","input_name":null,"label":null,"param":null,"default_option":null,"description":"Width","is_custom":false,"title":"Width:"},"513":{"property_id":513,"name":"Custom Property","input_name":null,"label":null,"param":null,"default_option":null,"description":"Custom Property","is_custom":true,"title":"Custom Property:"},"514":{"property_id":514,"name":"Custom Property","input_name":null,"label":null,"param":null,"default_option":null,"description":"Custom Property","is_custom":true,"title":"Custom Property:"},"515":{"property_id":515,"name":"Device","input_name":null,"label":null,"param":null,"default_option":null,"description":"Device","is_custom":false,"title":"Device:"}},"qualifiers":{"504":[{"property_id":302,"results":null,"aliases":null,"options":[341,342,343]}],"505":[{"property_id":304,"results":null,"aliases":null,"options":[347,348,349]}],"100":[{"property_id":300,"results":null,"aliases":null,"options":[301,327,328,335,336,337,329]}],"512":[{"property_id":306,"results":null,"aliases":null,"options":[338,339,340]}],"511":[{"property_id":301,"results":null,"aliases":null,"options":[332,331,333,334]}],"506":[{"property_id":305,"results":null,"aliases":null,"options":[350,351,352]}],"501":[{"property_id":303,"results":null,"aliases":null,"options":[344,345,346]}]},"category_id":null},"params":{"category_id":null,"taxonomy_id":null,"recipient_id":null},"type":"Variations_PropertySet","pagination":{}}

**Comment by mdg** [comment]
Hi Graeme,
This was reverted last night as part of another issue. We plan to reapply the change once we've confirmed it's not related to another problem.

**Comment by amitsnyderman** [comment]
Thanks @mdg. @gragra33, the revert has been reverted and should be returning the expected response now.

**Comment by mdg** [comment]
I concur. I'm now seeing the correct structure in the response.

**Comment by gragra33** [comment]
That would explain why I saw what I did yesterday.

Thanks. I've got more checking to do due to the complex nature of the data returned however initial inspection it appears to be the old structure without the new category_id field added.

**Comment by gragra33** [comment]
Testing was completed successfully and we re-enabled support several hours ago. So far our users are having no problems as previously encountered with this bug. So it appears the fix made by Etsy has resolved the problem.
