### ISSUE TITLE
V2 vs V3 - End of life?

### ISSUE THREAD

**Issue by villanus** [etsy/etsyapi#112]
What is the difference in v2 / v3 other than moving to Oauth 2?
I am trying to build a .net wrapper for etsy api, and want to make sure its going to be compatible with version 3.   Or will version 2 still be supported?

Also, what is the projected release schedule for v3?

**Comment by mdg** [comment]
Sorry, this isn't great news, but the v3 API is not currently scheduled for public release. Likewise, v2 will continue to be supported until the v3 API is published.

**Comment by villanus** [comment]
i think its great news, since there is nothing wrong with the v2 api.
question is when v3 is released will etsy keep v2 around for a signifigant timeframe?
its difficult to invest time in a project, knowing it will be retired.
