### ISSUE TITLE
Read/Post Convos

### ISSUE THREAD

**Issue by gragra33** [etsy/etsyapi#30]
API Support for an Existing website feature

**Comment by villanus** [comment]
+1.

**Comment by villanus** [comment]
@mdg, new convos should be supported where there is a TRUST relationship.  For example say a customer purchases from SHOP, the shop should then be able to convo the customer using the api.  This would be useful in situations where there are delays in shipping, thank you notes, etc.  

It would also make a lot of sense for those who offer customized items.  Some customized items take lots of communication after the sale.  Supporting this feature would allow a seller who sells custom mugs / tshirts / graphics to message buyers upon an order with a PROOF.   Totally makes sense.

Please consider allowing some level of trust verification, where a relationship is already in place.

**Comment by mdg** [comment]
We have no plans to add convos access at this time.
